### ISSUE TITLE
qualisys/miqus cost, alternatives?

### ISSUE THREAD

**Issue by dappertutto** [motiondescriptors/modosc#1]
Has modosc been tested w/different camera environments? What was the pricing for your setups? I'm hoping for some practical information for replicating your y/t setup. FWIW, this strikes me as the most significant contribution to kinect skeletal data, especially for max users. Isadora software will soon support other devices like orbbec and intel realsense. Have these been tested, and do you foresee this supporting for other systems?

**Comment by federicoVisi** [comment]
Hi, thanks for your interest! Currently modosc supports only Qualisys systems (Oqus/Miqus). We are planning to implement support for other marker-based systems (e.g. Optitrack, Vicon). The main purpose of modosc is to make it easier to work with multi-camera, marker-based mocap in Max.  We are aware that not everyone has access to a lab with such an expensive system, so we’re considering the idea of including objects to work with other motion-sensing devices. However, at the moment we want to make sure that everything works fairly well with marker-based mocap, so it might take a while before we implement support for other systems.

**Comment by federicoVisi** [comment]
Hi, thanks for your interest! Currently modosc supports only Qualisys systems (Oqus/Miqus). We are planning to implement support for other marker-based systems (e.g. Optitrack, Vicon). The main purpose of modosc is to make it easier to work with multi-camera, marker-based mocap in Max. We are aware that not everyone has access to a lab with such an expensive system, so we’re considering the idea of including objects to work with other motion-sensing devices. However, at the moment we want to make sure that everything works fairly well with marker-based mocap, so it might take a while before we implement support for other systems.
